import React from "react";
import { BookOpen, X, CheckCircle } from "lucide-react";

interface CurriculumGuideModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function CurriculumGuideModal({ isOpen, onClose }: CurriculumGuideModalProps) {
  if (!isOpen) return null;

  const grades = [
    {
      level: "ป.1 (Grade 1)",
      vocab: "150 - 200 words",
      themes: "Self, family, classroom objects, basic colors, animals, numbers 1-10",
      complexity: "Short phrases, single-word answers",
      examples: "Stand up, Sit down, Circle the cat, Match, Color",
    },
    {
      level: "ป.2 (Grade 2)",
      vocab: "250 - 300 words",
      themes: "My family, house, food, body parts, animals",
      complexity: "Simple sentences, Yes/No questions, basic Wh-questions",
      examples: "Is this an apple? What is this? How many dogs? Where is the ball?",
    },
    {
      level: "ป.3 (Grade 3)",
      vocab: "350 - 450 words",
      themes: "Daily activities, hobbies, basic emotions, weather, food",
      complexity: "Basic single clauses, expressing basic feelings and needs",
      examples: "I like swimming. I am happy today. I want milk. What is the weather like?",
    },
    {
      level: "ป.4 (Grade 4)",
      vocab: "550 - 700 words",
      themes: "Abstract terms (love, help, time, work), simple steps",
      complexity: "Introduction of sequence words, past tense (was/were, regular verbs)",
      examples: "First, wash the apple. Next, cut it. He was at the library yesterday.",
    },
    {
      level: "ป.5 (Grade 5)",
      vocab: "750 - 950 words",
      themes: "Environment, occupations, travel, health, brief narratives",
      complexity: "Compound sentences, giving reasons using 'because', main ideas",
      examples: "I like cats because they are cute. She is a doctor because she loves helping.",
    },
    {
      level: "ป.6 (Grade 6)",
      vocab: "1,050 - 1,200 words",
      themes: "Festivals, simple history, technology, global issues, folktales",
      complexity: "Compound and complex ideas, advanced Wh-questions (Why, How)",
      examples: "Why do we celebrate Songkran? How do you make a paper bird? Short essays.",
    },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/55 no-print">
      <div className="w-full max-w-4xl max-h-[90vh] bg-[#F4F7F2] rounded-2xl shadow-2xl overflow-hidden border border-[#B8CC9A] flex flex-col">
        {/* Header */}
        <div className="p-6 bg-[#D4E4BC] text-[#3E4A2E] border-b border-[#B8CC9A] flex justify-between items-center">
          <div className="flex items-center space-x-3">
            <BookOpen className="w-6 h-6 text-[#6B8E23]" />
            <h2 className="text-xl font-bold font-friendly">Thai Primary School English Curriculum Rules</h2>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 rounded-full hover:bg-[#F4F7F2] text-[#3E4A2E] transition cursor-pointer"
            aria-label="Close"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-6 text-[#3E4A2E]">
          <p className="text-[#556B2F] text-sm md:text-base leading-relaxed">
            The worksheets generated by <strong>English Magic Primary</strong> strictly adhere to the official standards set by the 
            <strong> Thai Ministry of Education</strong>. Use this reference guide to align your lesson planning with curriculum constraints.
          </p>

          <div className="overflow-x-auto rounded-xl border border-[#E1E8D8] shadow-sm bg-white">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-[#E1E8D8] text-[#3E4A2E] font-friendly text-sm border-b border-[#B8CC9A]">
                  <th className="p-3 font-bold whitespace-nowrap">Grade Level</th>
                  <th className="p-3 font-bold whitespace-nowrap">Vocab Size</th>
                  <th className="p-3 font-bold">Themes & Keywords</th>
                  <th className="p-3 font-bold">Grammar & Complexity</th>
                  <th className="p-3 font-bold">Core Examples</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E1E8D8]/60 text-gray-800 text-xs md:text-sm">
                {grades.map((g, idx) => (
                  <tr key={idx} className="hover:bg-[#F0FDF4]/50 transition">
                    <td className="p-3 font-bold text-[#3E4A2E] whitespace-nowrap">{g.level}</td>
                    <td className="p-3 font-bold text-[#6B8E23] whitespace-nowrap">{g.vocab}</td>
                    <td className="p-3 text-gray-600">{g.themes}</td>
                    <td className="p-3 text-gray-700 font-medium">{g.complexity}</td>
                    <td className="p-3 text-[#556B2F] italic font-handwritten font-semibold">{g.examples}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Quick Notes */}
          <div className="p-4 rounded-xl bg-[#F0FDF4] border border-[#B8CC9A]/40 text-[#556B2F] text-xs md:text-sm space-y-2">
            <h3 className="font-bold flex items-center text-[#3E4A2E]">
              <CheckCircle className="w-4 h-4 mr-2 text-[#6B8E23]" /> O-NET Aligned Design Best Practices:
            </h3>
            <ul className="list-disc pl-5 space-y-1 text-gray-700 leading-relaxed">
              <li><strong>ป.1 - ป.3</strong> focus heavily on high-frequency nouns, adjectives, and immediate environments. Keep questions short and answers concrete.</li>
              <li><strong>ป.4 - ป.6</strong> introduce cognitive sequence words, connectors like <em>because</em>, and encourage paragraph analysis.</li>
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-[#E1E8D8] border-t border-[#B8CC9A]/40 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2 bg-[#6B8E23] text-white font-bold font-friendly rounded-lg hover:bg-[#556B2F] transition cursor-pointer"
          >
            Got it, Teacher!
          </button>
        </div>
      </div>
    </div>
  );
}
